# 기본적인 수학 개념들 {#math}

## 수열(sequence)과 수열의 극한(limit)

### 상한(supremum)과 하한(infimum)

수열은 극한이 존재하는 경우와 존재하지 않는 경우로 나누어 생각할 수 있다. 극한이 존재하지 않는 수열에서, **상계(upper bound)**와 **하계(lower bound)**의 점근적인 움직임(asymptotic behavior)를 고려해 볼 수 있을 것이다.

$\{x_{n}\}_{n=1}^{\infty}$를 실수로 구성된 수열(sequence)이라고 하자. 우선 상계와 하계를 다음과 같이 정의한다.

<div class="definition">

다음 조건을 만족하는
$$x_{n} \leq u \text{ 모든 } n \in \mathbb{N}$$
$u \in \mathbb{R}$을 수열 $\{x_{n}\}_{n=1}^{\infty}$의 **상계(upper bound)**라고 한다.

</div>

<div class="definition">

다음 조건을 만족하는
$$x_{n} \geq l \text{ 모든 } n \in \mathbb{N}$$
$l \in \mathbb{R}$을 수열 $\{x_{n}\}_{n=1}^{\infty}$의 **하계(lower bound)**라고 한다.

</div>

이들을 이용해 상한과 하한을 정의할 수 있다.

<div class="definition">

다음 조건을 만족하는
$$u_{l} \text{은 } \{x_{n}\}_{n=1}^{\infty} \text{의 상계이고 } \{x_{n}\}_{n=1}^{\infty} \text{의 다른 상계 } u \text{가 존재할 때 } u_{l} \leq u$$
$u_{l} \in \mathbb{R}$을 $\{x_{n}\}_{n=1}^{\infty}$의 **상한(supremum)**이라고 하며, 다음과 같이 표현한다.
$$u_{l}=\sup_{n\in\mathbb{N}}x_{n}$$

</div>

<div class="definition">

다음 조건을 만족하는
$$l_{u} \text{는 } \{x_{n}\}_{n=1}^{\infty} \text{의 하계이고 } \{x_{n}\}_{n=1}^{\infty} \text{의 다른 하계 } l \text{이 존재할 때 } l_{u} \leq l$$
$l_{u} \in \mathbb{R}$을 $\{x_{n}\}_{n=1}^{\infty}$의 **하한(infimum)**이라고 하며, 다음과 같이 표현한다.
$$l_{u}=\inf_{n\in\mathbb{N}}x_{n}$$

</div>

### 상극한(limit superior)과 하극한(limit infimum)

### 실함수의 수열들(sequences of real functions)

확률변수(random variable)의 수열이 함수의 수열처럼 여겨질 수 있다는 사실에서 함수의 수열의 성질을 이해하는 것은 중요하다. 일반적인 수열의 수렴에 관한 성질들과 비교했을 때 함수의 수열들의 수렴에 관한 성질에서는 여러 개의 정의로 다뤄질 수 있다는 점에서 차이가 있다. 가장 널리 알려진 함수의 수렴은 **점별수렴(pointwise convergence)**과 **균등수렴(uniform convergence)**이 있다.

<div class="definition">

$\{ f_{n}(x)\}_{n=1}^{\infty}$를 실함수의 수열이라고 하자. 그러면 모든 $x\in\mathbb{R}$에 대해
$$\lim_{n\rightarrow \infty}f_{n}(x)=f(x)$$
를 만족하는 실함수 $f$가 존재할 때 수열 $\{ f_{n}(x)\}_{n=1}^{\infty}$이 $f$에 **점별수렴(pointwise convergence)**한다고 한다. 여기서는 $n\rightarrow \infty$일 때
$$f_{n} \stackrel{pw}{\rightarrow} f$$
로 표현하기로 한다.

</div>

점별수렴보다 더 강한 조건으로 $x \in \mathbb{R}$에 상관 없이 모든 지점에서 동시에 $n\rightarrow\infty$일 때 $f_{n}(x) \rightarrow f(x)$이길 요구할 수도 있다. 이 때 사용되는 정의가 균등수렴이다.

<div class="definition">

$\{ f_{n}(x)\}_{n=1}^{\infty}$를 실함수의 수열이라고 하자. 그러면 모든 $\epsilon > 0$에 대해
$$|f_{n}(x)-f(x)| <\epsilon \forall n \geq n_{\epsilon} \text{ and } x\in \mathbb{R}$$
을 만족시키는 정수 $n_{\epsilon}$이 존재할 때 수열 $\{ f_{n}(x)\}_{n=1}^{\infty}$이 $f$에 **균등수렴(uniform convergence)**한다고 한다. 여기서는 $n\rightarrow \infty$일 때
$$f_{n} \stackrel{u}{\rightarrow} f$$
로 표현하기로 한다.

</div>

(두 수열의 차이점 설명)

## 연산자들(operators)

### 직합(direct sum)

<div class="definition">

크기 $m \times n$인 행렬 $\bm{A}$와 $p\times q$인 행렬 $\bm{B}$가 있을 때 이들의 **직합(direct sum)**은
$$\bm{A}\oplus\bm{B}=
\begin{bmatrix}
\bm{A} & 0\\
0 & \bm{B}\\
\end{bmatrix}
=
\begin{bmatrix}
a_{11} & \cdots & a_{1n} & 0 & \cdots & 0 \\
\vdots & \ddots & \vdots & \vdots & \ddots & \vdots \\
a_{m1} & \cdots & a_{mn} & 0 & \cdots & 0 \\
0 & \cdots & 0 & b_{11} & \cdots & b_{1q} \\
\vdots & \ddots & \vdots & \vdots & \ddots & \vdots \\
0 & \cdots & 0 & b_{p1} & \cdots & b_{pq} \\
\end{bmatrix}
$$

</div>

<div class="example">

$$
\begin{bmatrix}
1 & 3 & 2\\
2 & 3 & 1\\
\end{bmatrix}
\oplus
\begin{bmatrix}
1 & 6\\
0 & 1\\
\end{bmatrix}
=
\begin{bmatrix}
1 & 3 & 2 & 0 & 0\\
2 & 3 & 1 & 0 & 0\\
0 & 0 & 0 & 1 & 6\\
0 & 0 & 0 & 0 & 1\\
\end{bmatrix}
$$

</div>
