# 적분과 기댓값 {#expectation}

## 리만적분(Riemann integral)

구간 $[a,b]$에서 함수 $f(x)$의 **리만적분(Riemann integral)**은 부분합의 극한으로 정의된다. 우리는 구간 $[a,b]$를 $a=x_{0}<x_{1}<\ldots <x_{n} =b$로 나무어 다음과 같은 합을 만들 수 있다.
\begin{equation}
\sum_{i=1}^{n}f(\xi_{i})\Delta x_{i}.
 (\#eq:Riemannintegral)
\end{equation}
이 때  $\xi_{i}$는 $i$번째 구간 $[x_{i-1},x_{i})$에 있는 점이며 $\Delta x_{i}=x_{i}-x_{i-1}$이다. $\xi_{i}$와 $\Delta x_{i}$는 $n$과도 관련이 있음을 알아두자. 그러나 표기의 간편성을 위해 생략하기로 한다. 그러면 $\xi_{i}$를 어떻게 선택하는지와 상관없이 $n\rightarrow\infty$이고 $\max_{1\leq i \leq n}\Delta x_{i} \rightarrow 0$일 때 $f$를 **리만적분 가능(Riemann integrable)**하다고 말한다.

리만적분성은 $f$가 꽤 regular함을 요구한다. $x$가 유리수일 때 0, 아닐때 1을 갖는 함수 $f(x)$가 있다고 하자. 그러면 식 \@ref(eq:Riemannintegral)의 극한 $\int_{0}^{1}f(x)dx$는 중간값을 어떻게 고르냐에 따라 값이 달라지므로 리만적분 가능하지 않다. 모든 $i$에 대해 $\xi_{i}$를 유리수로 고르면 극한의 0이되나, 반대로 모든 $i$에 대해 무리수로 $\xi_{i}$를 잡을 경우 극한은 1이 된다. 그리고 $xi_{i}$를 유리수와 무리수를 섞어 잡을 경우 극한은 존재하지 않게 된다.

## 적분의 성질(properties of integration)

어떤 상황에서 적분과 극한의 순서를 바꿀 수 있을까?

```{theorem, name="단조수렴정리(MCT)"}

1. null set $N$ $(\mu(N)=0)$ 바깥의 $\omega$에 대해  $f_{n}(omega)\geq 0,\forall n$이고 $f_{n}(\omega)\uparrow f(\omega)$라고 하자. 그러면 $\int f_{n}(\omega)d(\omega)\uparrow \int f(\omega)d\mu(\omega)$이다.

2. 확률변수 버전으로는, 만약 모든 $n$에 대해 $P\{\omega: X_{n}(\omega)\geq 0 \forall n \text{ and } X_{n}(\omega)\uparrow X(\omega)\}=1$이라고 하자. 그러면 $E(X_{n})\uparrow E(X)$이다.

```

```{theorem, name="지배수렴정리(DCT)"}

1. null set $N$ $(\mu(N)=0)$ 바깥의 $\omega$에 대해  $f_{n}(omega) \rightarrow f(\omega)$이고 $|f_{n}(\omega) | \leq g(\omega)$, $\int g(\omega)d\mu(\omega) < \infty$일 때 $\int f_{n}(\omega)d\mu(\omega) \rightarrow \int f(\omega)d\mu(\omega)$이다.

2. 확률변수 버전으로는, 만약 모든 $n$에 대해 $P\{\omega: X_{n}(\omega)\rightarrow X(\omega) \text{ and } |X_{n}(\omega)|\leq Y(\omega) \forall n\}=1$이고 $E(Y)<\infty$라고 하자. 그러면 $E(X_{n})\rightarrow E(X)$이다.

```

지배수렴정리의 따름정리로 유계수렴정리(bounded convergence theorem, BCT)가 있다.

```{theorem, name="유계수렴정리(BCT)"}
$X_{n}$이 확률변수이고 $P\{X_{n}(\omega)\rightarrow X(\omega)\}=1$이며 각 $n$에 대해 $P\{|X_{n}|\leq c\}=1$ 일 때 ($c$는 상수), $E(X_{n})\rightarrow E(X)$이다.

```



## 부등식들(inequalities)

확률론에서 부등식들은 중요한 역할을 하는데, 대부분의 일들은 다른 것들로부터 특정한 확률로 추정하는 문제들을 다루고 있기 때문이다.

```{lemma, name="모멘트로부터 꼬리확률을 추정"}
$g$가 음이 아니고, 감소하지 않는 함수이며 $E\{g(X)\}<\infty$라고 하자. $x>0$일 때
$$P(|X|>x)\leq \frac{E\{g(|X|)\}}{g(x)}$$
이다.

```

```{proof}
\begin{eqnarray}
E\{g(|X|)\} &=& E\{g(|X|)\}I\{|X|>x\}\\
&=& g(x)EI\{|X|>x\}\\
&=& g(x)P(|X|>x).
\end{eqnarray}

```

$g$를 특수하게 설정할 경우 다음 정리를 얻는다.

```{theorem, name="마르코프 부등식"}
어떤 $r>0$에 대해 $E|X|^{r}<\infty$라고 하자. 만약 $x>0$이면 다음 부등식이 성립한다.
$$P(|X|>x)\leq \frac{E|X|^{r}}{x^{r}}.$$

```

```{corollary, name="체비셰프 부등식"}
만약 $X$가 평균 $\mu$, 분산 $\sigma^{2}$을 갖는 확률변수라면 $c>0$에 대해 $P(|X-\mu|\geq c) \leq \sigma^{2}/c^{2}$이다.

```

```{theorem, name="젠슨 부등식"}
$f(x)$가 convex 함수이고 $X$는 유한한 평균 $\mu$를 갖는 확률변수라고 하자. 만약 $E(|f(X)|)<\infty$이면, $E\{f(X)\}\geq f\{E(X) \}$이다.

```

```{corollary, name="젠슨 부등식의 따름정리"}
만약 $X$가 어떤 확률변수이고 $p\geq 1$이면 $E(|X|)\leq \{ E(|X|^{p}) \}^{1/p}$이다.

```




