# 회귀분석 {#reg}

AIC, AICc, BIC

## 선형모형(linear model)

### 단순선형모형(simple linear model)

이 절의 내용은 [@Yee2015]를 따른다. [@Wood2006]도 참고한다. 다음과 같이 $n$개의 관찰값 $x_{i},y_{i}, i=1,\ldots,n$이 있다고 하자. 이 때 $y_{i}$는 평균이 $\mu_{i}=E(Y_{i})$인 확률변수 $Y_{i}$의 관찰값이라고 하자. 그러면 $x$와 $y$ 사이에 가장 단순한 형태의 선형모형을 세울 수 있다.
$$Y_{i}=\mu_{i}+\epsilon_{i}, \qquad{\mu_{i}=x_{i}\beta}.$$
이 때 $\beta$는 알려지지 않은 **모수(parameter)**이며 $\epsilon_{i}$는 보통 상호 독립이면 평균이 0인 확률변수라고 가정한다. $Y$는 보통 **설명변수(response variable)**라고 부르며, $x$는 **예측변수(predictor variable)**라고 부른다.

### 단순 최소제곱 추정(simple least squares estimation)

그렇다면 우리는 자료 $(x_{i},y_{i})$들로부터 $\beta$를 어떻게 추정할 수 있을까? 가장 합리적인 방법으로 자료를 가장 잘 적합(fit)하는 $\hat{\beta}$로 $\beta$를 추정할 수 있다.


## 선형혼합모형(linear mixed model)

이 부분의 내용은[@Wood2006]를 참고하였다. 일반적으로 **선형혼합모형(linear mixed model)**은 선형모형을 확장한 것이다.
$$\mathbf{y}=\mathbf{X}\boldsymbol{\beta}+\boldsymbol{\epsilon}, \qquad{\boldsymbol{\epsilon}\sim\mathcal{N}(0,\boldsymbol{\Lambda}_{\theta})}.$$
이 때
$$\mathbf{y}=\mathbf{X}\boldsymbol{\beta}+\mathbf{Zb}+\boldsymbol{\epsilon},$$
$$\mathbf{b}\sim\mathcal{N}(\mathbf{0},\boldsymbol{\psi}_{\theta}),$$
$$\boldsymbol{\epsilon}\sim\mathcal{N}(\mathbf{0},\boldsymbol{\Lambda}_{\theta})$$
이다. $\mathbf{b}$는 무작위 벡터로 **무작위 효과(random effects)**를 나타낸다. $\mathbf{b}$는 기댓값이 0이고 공분산 행렬은 알려지지 않은 모수 $\theta$를 포함한 $\boldsymbol{\psi}_{\theta}$를 갖는다. $\mathbf{Z}$는 무작위 효과를 나타내는 모형 행렬(model matrix)이다. $\boldsymbol{\Lambda}_{\theta}$는 양정치(positive definite) 행렬로 residual의 autocorrelation을 모델링하는데 사용한다. 만약 $\boldsymbol{\Lambda}_{\theta}=\mathbf{I}\sigma^{2}$이면 $\mathbf{b}$와 $\boldsymbol{\epsilon}$은 독립이다.

### 무작위 요인인 한 개일 때(a single random factor)

[@Wood2006]를 참고하였다. 이 때의 모형은
$$y_{ij}=\alpha +b_{i}+e_{ij}$$
이다. 
