# 칼만 필터 {#kalman}

자연계에서 나타나는 시계열은 많은 경우, 직전의 상태와 밀접하 관계를 갖으면서 끊임없이 변화하는 형태를 보이고 있어 선형모형으로는 예측의 정확도를 높이는 데 한계가 있을 때가 있다. 실제와 닮은 모형이 더 우수하다는 원칙에서 동적모형에 대한 연구와 적용이 예보의 정확성을 높여줄 것이다.

**칼만필터(kalman filter)**란 공정제어를 위해 칼만(Kalman)이 1960년 제안한 알고리즘으로, 시간의 흐름에 따라 모형식이 변화하는 동적 모형(dynamic model)으로 선형과 비선형의 중간 형태를 지니고 있다고 한다. 예측 문제도 해결하는 등 여러 가지 장점이 있어 경제 에측, 신호 처리, 기상 예보 등 응용 범위가 넓은 동적 모형이라고 한다.

칼만 필터 모형은 다음의 생성 구조로 이루어진다.

1. 초기치가 필요하다.

2. 주어진 **상태방정식(state equation)**에 의해 전 상태로부터 내적오차와 합하여 현 상태값이 결정되며,

3. 주어진 **출력방정식(output equation)**에 의해 고려된 입력변수값과 동적회귀계수 역할을 하는 현 상태의 내적과 출력오차의 합 형태로 관측치가 생성된다는 가정 아래 구성된 모형으로,

4. 새로운 관측치가 얻어지면, 모형이 **최신화(updating)**되도록 알고리즘이 주어져야 한다.

$F_{t}$, $G_{t}$, $W$, $V$, $m_{0}$, $C_{0}$, $t=1,2,\ldots,$ 가 주어진 경우 다음의 생성식으로 이루어진 모형식을 칼만필터 모형이라고 한다.

$$\text{(초기 분포) } \theta_{0} \sim \mathcal{N}(m_{0},C_{0})$$
$$\text{(상태방정식) } \theta_{t}=G_{t}\theta_{t-1}+w_{t}, \qquad{w_{t} \sim \mathcal{N}(0,W)}$$
$$\text{(출력방정식) } Y_{t}=F_{t}\theta_{t}+v_{t}, \qquad{v_{t}\sim \mathcal{N}(0,V)}$$

여기에서 

- $\theta_{t}$: **상태벡터(state vector)**

- $G_{t}$: **전이행렬(transition matrix)**

- $w_{t}$: **내적오차벡터(innovational error vector)**

- $Y_{t}$: **관측치(observation)**

- $F_{t}$: **입력벡터(input vector)**로 상태벡터가 관측치에 영향을 주는 설명변수들로 이루어져있음

- $v_{t}$: **출력오차(output error)**

$\theta_{t-1}$과 $w_{t}$는 독립이며, $\theta_{t}$는 $v_{t}$와 독립이고, 두 오차는 서로 독립이다.

칼만필터 모형은 두 개 이상의 선형식의 모임으로 연결되어 있으므로 전체적으로는 비선형적 특성을 지니고 있고, 각 식은 선형모형이므로 모형의 설명력과 예측력이 우수하며, 이론적 전개가 용이하다.

```{example, name="칼만필터 모형의 예"}
시간에 따라 생성되는 종속변수가 하나이며 설명변수가 두 개인 선형모형을 생각해보자.

1. 회귀모형은 회귀계수가 미지의 상수인 경우로 정적 모형이다. 즉
$$Y_{t}=m_{0}+m_{1}X_{1t}+m_{2}X_{2t}+v_{t}$$
인 형태가 된다.

2. 회귀동적모형은 회귀계수가 시간에 따라 변화하는 경우로 동적모형이다. 즉
$$Y_{t}=m_{0t}+m_{1t}X_{1t}+m_{2t}X_{2t}+v_{t}$$
인 형태가 되며 각 회귀계수들을 함수형태로 추정해 주어야 한다.

3. 회귀동적선형모형은 회귀계수가 전 시점의 회귀계수에 의하여 결정되는 경우로 회귀동적모형의 특수한 경우가 된다. 예를 들어, 전이행렬이 단위행렬인 경우(상태벡터가 임의보행인 경우)
$$Y_{t}=m_{0t}+m_{1t}X_{1t}+m_{2t}X_{2t}+v_{t}$$

그리고

$$
\theta_{t} =
 \begin{pmatrix}
  m_{0t} \\
  m_{1t} \\
  m_{2t} 
 \end{pmatrix}
= 
 \begin{pmatrix}
  1 & 0 & 0 \\
  0 & 1 & 0 \\
  0 & 0 & 1
 \end{pmatrix}
 \begin{pmatrix}
  m_{0,t-1} \\
  m_{1,t-1} \\
  m_{2,t-1} 
 \end{pmatrix} 
+
 \begin{pmatrix}
  w_{0t} \\
  w_{1t} \\
  w_{2t} 
 \end{pmatrix}
$$
이와 같은 형태를 지닌다.

```

## 칼만필터 모형의 종류(types of Kalman filter)

### 은닉 마르코프 모형(hidden Markov model)

오차항이 없는 칼만필터 모형으로 다음과 같다.

$$
\begin{cases}
\mu_{t}=G\mu_{t-1} \\
Y_{t}=F\mu_{t}.\\
\end{cases}
$$

여기서 전이행렬 $G$와 출력행렬 $F$는 시간에 따라 변화하지 않으므로 상태방정식은 확률과정에서의 상태벡터 $\mu_{t}$의 전이행렬이 $G$인 마르코프 연쇄로 생각할 수 있다. 관측치 $Y_{t}$만 주어져 있고 $\mu_{t}$는 모르는 경우 모수 $G$와 $F$를 추정하여 생성구조를 완성하는 과정을 이룬다. 은닉 마르코프 모형은 범주형 자료에도 적용이 가능하며, 신호처리에 바탕을 두고 있는 음성인식, 영상인식, 문장인식에 널리 사용되고 있는 통계적 기법이다.

### 일차 칼만필터 모형(simple Kalman filter model)

**일차 칼만필터 모형(simple Kalman filter model)**은 오차항을 포함한 칼만필터 모형 중 가장 간단한 형태로 $t$ 시점의 상태열이 임의보행과정(random walk)으로 직전 상태값 주위에서 흔들리며 변화할 때 사용한다.

$$
\begin{cases}
\mu_{t}=\mu_{t-1}+w_{t} \\
Y_{t}=\mu_{t}+v_{t}.\\
\end{cases}
$$

### 회귀 칼만필터 모형(regression Kalman filter model)

**회귀 칼만필터 모형(regression Kalman filter model)**은 입력변수(설명변수)가 있는 경우에 사용하는 동적모형으로 계수(상태열)가 시간에 따라 변화하는 동적 계수가 된다.

$$
\begin{cases}
\theta_{t}=\theta_{t-1}+w_{t} \\
Y_{t}=F_{t}\theta_{t}+v_{t}.\\
\end{cases}
$$

### 일반적 칼만필터 모형(general Kalman filter model)

**일반적 칼만필터 모형(general Kalman filter model)**은 회귀 칼만필터 모형에서 동적 계수가 임의보행이 아닌 경우에 전이행렬을 고려하는 동적모형이다.

$$
\begin{cases}
\theta_{t}=G_{t}\theta_{t-1}+w_{t} \\
Y_{t}=F_{t}\theta_{t}+v_{t}.\\
\end{cases}
$$

### 확장된 칼만필터 모형(extended Kalman filter model)

칼만필터 모형에서 상태방정식과 출력방정식이 선형모형이 아닌 비선형모형인 경우를 **확장된 칼만필터 모형(extended Kalman filter model)**이라고 한다. 추정과 최시노하는 주어진 식을 선형화하여 해결하며, 시스템에 대한 물리적 이해가 필요하다.

$$
\begin{cases}
\theta_{t}=f(\theta_{t-1},w_{t}) \\
Y_{t}=h(\theta_{t},v_{t})\\
\end{cases}
$$

## 최신화 알고리즘(updating algorithm)

**칼만필터링(Kalman filtering)**은 칼만필터 모형의 상태열 $\{ \theta_{t}\}$의 추정에 사용된다. 칼만필터링은 다음의 특징을 지니고 있어 이공계 분야 모델링에 많이 응용된다.

- 미지의 상태열 $\{\theta_{t}\}$를 추정하는 반복처리과정이다.

- 동적처리기법이다. 즉 시간의 흐름에 따라 진행하면서 과거와 현재의 출력값들을 보고 현재의 상태를 추정해간다.

- 평균제곱오차를 최소로 하는 최적 상태열을 추정하는 통계적 이론을 바탕으로 한다.

- 체계적 기법(systematic method)이다. 즉 일단 칼만필터 모형이 만들어지면 칼만필터 알고리즘을 쉽게 사용할 수 있다.

- 나쁜 초기치의 영향이 오래가지 않는다. 즉 로버스트하다.

- 프로그래밍이 쉽다.

칼만필터링은 다변량 정규분포이론에 근거하며 최적 상태값을 추정하는 아래와 같은 **동적순환과정(dynamic recursive procedure)**으로 이루어진다. 이를 **최신화 알고리즘(updating algoritm)**이라고 한다. $t=1,2,\ldots$로 변화시키며

1. $t-1$시점까지의 모든 정보 $D_{t}$에 의한 $\theta_{t-1}$의 분포
$$\theta_{t-1}|Y_{t-1} \sim \mathcal{N}(m_{t-1},C_{t-1})$$

2. $t$시점에서의 $\theta_{t}$의 사전분포: 상태방정식 $\theta_{t}=G_{t}\theta_{t-1}+w_{t}, w_{t} \sim \mathcal{N}(0,W_{t})$에 의하여,
$$\theta_{t}|D_{t-1} = (G_{t}\theta_{t-1}+w_{t})|D_{t-1}\sim \mathcal{N}(a_{t},R_{t})$$
여기에서 $a_{t}=G_{t}m_{t-1}, R_{t}=G_{t}C_{t-1}G_{t}'+W_{t}$이다.

## 동적선형모형(dynamic linear model)

## R-예제(R-dlm)
