# 전이함수모형 {#transfer}

시차회귀분석(lagged regression)

입력시계열과 출력시계열로 사용되는 시계열 사이의 관계를 회귀모형의 형태로 표현한 것을 **전이함수(transfer function)**라고 하며, 이 떄의 모형을 **전이함수모형(transfer function model)**이라고 한다. 일반적으로 전이함수 모형은 입력시계열이 출력시계열에는 영향을 미치나 반대의 영향은 없다는 가정 하에서 사용한다. 만약 출력시계열도 입력시계열에 영향을 미치는 경우에는 전이함수 모형 대신 벡터 ARIMA 모형을 이용한 분석을 한다.

\begin{equation}
y_{t}=\sum_{j=0}^{\infty}\alpha_{j}x_{t-j}+\eta_{t}=\alpha(B)x_{t}+\eta_{t}
(\#eq:lagreg)
\end{equation}

라고 모형을 세우자. 이 때 $x_{t-j}$는 입력시계열, $\eta_{t}$는 잡음과정이 되며
$$\alpha(B)=\sum_{j=0}^{\infty}\alpha_{j}B^{j}$$
는 전이함수가 된다. 이 때 $\alpha_{j}$를 **충격반응가중값(impulse response weight)**이라고 부른다.

Box와 Jenkins에 따르면, $x_{t}$와 $\eta_{t}$에 ARIMA모형을 적합한다. 이 때
$$\phi(B)x_{t}=\theta(B)w_{t} \text{ and }$$
$$\phi_{\eta}(B)\eta_{t}=\theta_{\eta}(B)z_{t}$$
로 표현할 수 있다. 이 때

- $w_{t},z_{t}$는 독립이고 분산이 $\sigma_{w}^{2}$, $\sigma_{z}^{2}$인 백색잡음과정이다. Box와 Jenkins는 $\alpha_{j}, j=1,2,\ldots$의 형태로 systematic patteren들이 관찰될 수 있고 이들을 a ratio of polynomials involving a small number of coefficients, along with a specified delay $d$로 표현할 수 있다고 한다. 따라서

$$\alpha(B)=\frac{\delta (B)B^{d}}{\omega(B)}$$
로 표현할 수 있고(이렇게 표현하면 추정해야 할 모수의 숫자를 줄일 수 있다고 한다), 여기서
$$\omega(B)=1-\omega_{1}B-\omega_{2}B^{2}-\cdots -\omega_{r}B^{r}$$
이며
$$\delta(B)=\delta_{0}+\delta_{1}B+\cdots +\delta_{s}B^{s}$$
들이 지시연산자가 된다. 식 (\@ref(eq:lagreg))를 정리하면
$$\tilde{y}_{t}=\frac{\phi(B)}{\theta(B)}y_{t}=\alpha(B)w_{t}+\frac{\phi(B)}{\theta(B)}\eta_{t}=\alpha(B)w_{t}+\tilde{\eta}_{t}$$
를 얻게 된다. 이 때

- $\alpha(B)=\sum_{j=0}^{\infty}\alpha_{j}B^{j}$: 전이함수

- $\tilde{\eta}_{t}$: 변환된 잡음으로 $w_{t}$와 독립

- $\frac{\phi(B)}{\theta(B)}$: **선형필터(linear filter)**라 부름

- $w_{t}$: 사전백색화된 input series

- $\tilde{y}_{t}$: 변환된 output series



전이함수모형의 기본 가정은 입력시계열과 반응시계열이 모두 정상시계열이라는 것이다. 따라서 먼저 분석에 사용될 시계열들이 정상성을 갖는지 여부를 판단해야 한다.

## 안정성과 인과성(stability and causality)

(조신섭 교수님 책 참고)

## 교차상관함수(cross-covariance function)

전이함수의 형태를 식별하기 위해서는 충격반응가중값을 먼저 구해야 하는데, 이를 위해 두 개의 시계열 사이의 상관의 정도와 방향을 나타내는 교차상관함수를 이용한다.

```{definition, name="교차상관함수"}
정상인 두 시계열 $X_{t}$와 $Y_{t}$ 사이의 교차상관함수는
$$\gamma_{XY}(t)=E[(X_{t}-\mu_{X})(Y_{t+k}-\mu_{Y})], \qquad{k=0,\pm 1, \pm 2, \ldots}$$
이다. 단 모든 $t$에 대해 $\mu_{X}=E[X_{t}]$, $\mu_{Y}=E[Y_{t}]$이다.

```

교차상관함수의 성질 중 중요한 것은 **자기상관함수와는 달리 대칭이 아니라**는 점이다. 따라서 교차상관함수는 자기상관함수와는 달리 상관의 정도와 영향을 미치는 방향을 같이 측정한다는 점이 특징이다.

```{definition, name="교차상관계수"}
정상인 두 시계열 $X_{t}$와 $Y_{t}$ 사이의 교차상관함수는
$$\rho_{XY}(k)=Corr(X_{t},Y_{t+k})=\frac{\gamma_{XY}(k)}{\sigma_{X}\sigma_{Y}}=\frac{\gamma_{XY}(k)}{\sqrt{\gamma_{X}(0)\gamma_{Y}(0)}}$$
으로 정의한다.

```

앞선 모형에서 $\tilde{y}_{t}$와 $w_{t}$의 교차상관계수는
$$\gamma_{\tilde{y} w}(h)=E[\tilde{y}_{t} w_{t}]=E[\sum_{j=0}^{\infty}\alpha_{j}w_{t+h-j}w_{t}]=\sigma_{w}^{2}\alpha_{h}$$
로 쓸 수 있다. 이는 $j=h$일 때를 제외하고 백색잡음의 ACF가 0임을 이용하는 것이다. 이 관계식을 보면
$$\hat{\alpha}_{h}=\frac{\hat{\gamma}_{\tilde{y}w}(h)}{\hat{\sigma}_{w}^{2}}$$
임을 유추해 낼 수 있다.

## 전이함수모형의 적합(fitting transfer function model)

1. 먼저 분석에 이용될 시계열들이 정상이라는 가정을 만족하도록 정상화한다.

2. 전이함수모형의 식별을 위해 시계열을 사전백색화(prewhitening)한다.

3. 잠정적인 전이함수모형을 추정한다.

4. 장차를 이용하여 오차모형을 식별하고 추정한다.
