# 변동도의 추정 {#variogramest}

이 문서에서는 variogram을 어떻게 추정할 것인지에 대해 다룰 것이다. 크게 두 가지가 있다.

- Empirical model (nonparametric)

- Parametric fit

그리고 [@Gelfand2010]의 33쪽부터, [@Cressie1993]의 69쪽부터 참고했다.

## 경험변동도(empirical variogram)

이것은 변동도를 비모수 추정하는 것이다. 다시 한 번 변동도의 정의를 살펴보면
$$2\gamma(\mathbf{h})=\text{Var}(Z(\mathbf{s}+\mathbf{h})-Z(\mathbf{s}))$$
으로 lag $\mathbf(h)$에만 의존하는 함수이다. 그런데 내재정상성(instinsic stationary)에서는 평균이 0이므로 
$$2\gamma(\mathbf{h})=E[Z(\mathbf{s}+\mathbf{h})-Z(\mathbf{s}))^{2}]$$
이 된다.

다음은 추정량을 구하기 위한 방법들이다.

1. 적률 추정(Metohd of moment (MoM) estimation (Matheron, 1962))

$E(Z(\mathbf{s}))=\mu$라는 상수 평균(constant mean) 가정하에 적률추정량(MoM estimator)은
$$2\hat{\gamma}(\mathbf{h})=\frac{1}{|N(\mathbf{h})|}\sum_{(s_{i},s_{j})\in N(\mathbf{h})}(Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j}))^{2}, \mathbf{h}\in \mathbb{R}^{d}$$
이다. 여기서 $N(\mathbf{h})$는 거리가 $\mathbf{h}$가 되는 $(\mathbf{s}_{i},\mathbf{s}_{j})$들의 집합이다. 즉
$$N(\mathbf{h})=\{ (\mathbf{s}_{i},\mathbf{s}_{j}), \mathbf{s}_{i}-\mathbf{s}_{j}=\mathbf{h} \}$$
이다. $N(\mathbf{h}) \neq N(\mathbf{-h})$임에 주의하자. 이 추정량의 문제는 **정규 격자(regular grid)** 자료에만 잘 적용된다는 점이다. Irregular한 자료에서는 $\mathbf{h}$에 대응되는 $N(\mathbf{h})$가 공집합(empty set)일 수도 있다. 그런 상황을 해결하기 위해 $\mathbf{h}$의 적당한 근방(neighborhood) $T(\mathbf{h})$을 생각하여 $N(\mathbf{h})$를 정의하기도 한다.
$$N(\mathbf{h})=\{ (\mathbf{s}_{i},\mathbf{s}_{j}), \mathbf{s}_{i}-\mathbf{s}_{j}=T(\mathbf{h}) \} .$$

그렇다면 이 근방의 size는 어떻게 정해야 할 것인가라는 질문이 생길 수도 있다. 이것은 **띠너비 선택(bandwidth selection)** 문제와 유사하다. Practically하게 [@Journel2003]는 $| \cup \{N(\mathbf{h}): \mathbf{h} \in T(\mathbf{h}) \} |$에 들어가는 distinct pair들이 적어도 30개 이상이 되도록 잡는 것이 좋다고 하였다. 

그러나 이 경우도 역시 데이터의 사이즈가 적을 경우 문제가 된다. 또한 $\mathbf{h}$의 방향도 고려할 경우 자료가 더 부족해지고, $\mathbf{h}$에 따라 pair 갯수 또한 차이가 난다. 그리고 자료로 인해 관측할 수 있는 $\mathbf{h}$의 minimum과 maximum length가 존재한다. 역시 practically하게 $\mathbf{h}$는 observation location들의 maximum length의 절반 정도를 고르도록 권장하고 있다.

마지막으로 이 추정량의 성질에 대해 알아보자. 우선 unbiased하다(특히 grid 자료인 경우). 그러나 outlier에 로버스트하지는 않다. $Z(\mathbf{s})$가 Gaussian distribution이면
$$(Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j}))^{2} \sim 2 \gamma(\mathbf{h})\chi_{1}^{2}$$
이다. 그런데 카이제곱 분포는 매우 skewed된 분포인데 이 분포를 sample mean을 이용해 추정했으므로 finite sample 이용시 variation이 클 수 있다.

2. 로버스트 추정량(robust estimator (Cressie and Howkins, 1980))

이 문제를 해결하기 위해 Cressie와 Howkins는 robust한 통계량을 제시하였다.
$$2 \bar{\gamma}(\mathbf{h})=\frac{1}{0.457+\frac{0.494}{|N(\mathbf{h})|}}\{\frac{1}{|N(\mathbf{h})|}\sum_{(\mathbf{s}_{i},\mathbf{s}_{j} \in N(\mathbf{h}))} |Z(\mathbf{s}_{i}-Z(\mathbf{s}_{j})|^{\frac{1}{2}}\}^{4}.$$
앞의 $\frac{1}{0.457+\frac{0.494}{|N(\mathbf{h})|}}$는 bias correction term이다.

이 추정량의 아이디어는 다음과 같다. 어떤 확률변수 $X \sim \chi_{1}^{2}$때 $X^{\frac{1}{4}}$는 거의 symmetric임을 보일 수 있다고 한다. 즉 $|Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j})|^{2}$보다는 $|Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j})|^{\frac{1}{2}}$이 더 symmetric하게 행동할 수 있을 것이다. 따라서 이것을 이용하고자 하는 것이다. $\mathbf{X}_{n}$을  $X_{n}\equiv\frac{1}{|N(\mathbf{h})|}\sum_{(\mathbf{s}_{i},\mathbf{s}_{j} \in N(\mathbf{h}))} |Z(\mathbf{s}_{i}-Z(\mathbf{s}_{j})|^{\frac{1}{2}}$ 이라고 하자.

다음은 $X \sim \chi_{1}^{2}$시 몇 가지 계산 결과이다.
$$E(X^{\frac{1}{4}})=0.82216, \text{Var}(X^{\frac{1}{4}})=0.12192, E(X_{n})=0.82216 \equiv \nu$$
$$\text{Var}(X_{n})=\frac{0.12192}{|N(\mathbf{h}|)} \text{(cross-covariance 무시할 경우)} .$$
그 다음 $f(x)=x^{4}$에 대해 $\nu$ 근방에서 테일러 전개를 해보자. 그러면
$$f(X_{n})\circeq f(\nu) +f'(\nu)(X_{n}-\nu)+\frac{1}{2}f''(\nu)(X_{n}-\nu)^{2} .$$
여기서 $X_{n}$만 random이다. 기댓값을 취하면
$$
\begin{aligned}
E(X_{n})^{4}&\circeq f(\nu) + f'(\nu)E(X_{n}-\nu) +\frac{1}{2}f''(\nu)E(X_{n}-\nu)^{2}\\
&\circeq 0.457 + 0 +\frac{0.494}{|N(\mathbf{h})|} \text{(second order까지 bias correction)}\\
\end{aligned}
$$
따라서 robust estimator 앞에 bias correction을 위한 숫자항이 붙는 것이다.

3. 또 다른 로버스트 추정량(another robust estimator)

특별한 이름은 없으며 앞 estimator에서 약간 변형한 형태이다.
$$
\begin{aligned}
2\tilde{\gamma}(\mathbf{h})&=\frac{1}{0.457}\text{Median}\{ |Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j})|^{2} , (\mathbf{s}_{i},\mathbf{s}_{j})\in N(\mathbf{h}) \}\\
&=\frac{1}{0.457}\{\text{Median} \{ |Z(\mathbf{s}_{i})-Z(\mathbf{s}_{j})|^{\frac{1}{2}} \}^{4} \}
\end{aligned}
$$
Median을 쓸 경우 제곱근을 한 다음 네제곱을 하거나 그냥 제곱을 하거나 차이가 없다고 한다.


## 경험변동도를 이용한 모수적 모형 추정(fitting parametric models to empirical variogram)

empirical variogram 자료들을 가지고 왜 또 parametric한 fitting을 하려고 할까? Geostatistics에서는 dependence structure $\boldsymbol{\sigma}$를 이용한 prediction에 관심이 있다. 그런데 prediction을 하려면 $\boldsymbol{\sigma}^{-1}$이 필요하다. 그런데 empirical variogram으로 하면 $\boldsymbol{\sigma}$가 non-negative definite가 아니거나 numerical singularity가 생긴다. 일반적으로 다음과 같은 모수 모델
$$\hat{\boldsymbol{\gamma}}(h;\hat{\boldsymbol{\theta}})$$
는 positive definite function을 guarantee한다(물론 numerical singular한 경우도 있을 수는 있다). 이러한 이유로 공간통계학에서는 모수를 이용한 모델링을 선호하는 것이다.

다음과 같이 $\hat{\gamma}(\mathbf{h}_{1}), \cdots , \hat{\gamma}(h_{m})$이 available하다고 하자(이들을 새로운 자료로 생각해도 좋다). 여기서 $m$은 고정시킨다. 우리의 목표는 $\boldsymbol{\gamma}(h;\boldsymbol{\theta})$가 true model일 때 $\hat{\boldsymbol{\gamma}}(h;\hat{\boldsymbol{\theta}})$를 만들고자 한다. 추정 방법은 크게 세 가지가 있다.
