# 공분산함수 {#covfct}

**공분산함수(covariance function)** $C(\mathbf{h})$는

$$C(\mathbf{h})=\text{Cov}(Z(\mathbf{s}+\mathbf{h}), (Z(\mathbf{s}), \qquad{C(\cdot); \mathbb{R}^{d} \rightarrow \mathbb{R}}$$
이다. 우리가 공분산함수를 고려할 때 생각해 볼 점은 공분산함수가 되기 위한 조건은 무엇이냐는 것이다.

공분산함수가 되려면 그 함수가 **양정치함수(positive definite function)**이어야 한다. 이것은 대응되는 행렬이 **비음정치(non-negative definite)** 또는 **양반정치(positive semi-definite)**이어야 한다는 것이다.

함수가 **순양정치함수(strictly positive definite function)**이어야 한다는 것은 대응되는 행렬이 **양정치(positive definite)**이어야 한다는 것이다.

그러나 저 둘을 보이는 것은 모든 유한한 표본에 대해 항상 성립해야 하는 것을 보여야하기 때문에 어렵다. 이를 좀 더 쉽게 보일 수 있는 방법으로 Bochner (1933, 1955)의 정리를 이용하는 것이다.

## 스펙트럴 표현 정리(spectral representation theorem)

**스펙트럴 표현 정리(spectral representation theorem)**는 다른 말로 **Bochner의 정리(Bochner's theorem)**이라고 부른다.

<div class="theorem">

실수값을 갖는 연속 함수 $C$가 양정치함수라는 것은 그 함수가 symmetric nonnegative measure $F$로부터 $\mathcal{R}^{d}$로 가는 Fourier transform인 경우이다. 즉 

$$
\begin{eqnarray}
C(\mathbf{h})&=&\int_{\mathbb{R}^{d}}\exp(i\mathbf{h}^{T}\mathbf{x})dF(\mathbf{x})\nonumber\\
&=&\int_{\mathbb{R}^{d}}\cos(\mathbf{h}^{T}\mathbf{x})dF(\mathbf{x}) \text{ (spectral representation)}
\end{eqnarray}
$$

</div>

인 경우이다. 여기서 $F$를 **스펙트럼 측도(spectral measure)**라고 한다. 만약 $F$가 좋은 성질을 갖고 있어서 **(르베그) 밀도함수((Lebesgue) density function)** $f$가 있으면, 즉 $F(\mathbf{x})=f(\mathbf{x})d\mathbf{x}$이면 $f(\mathbf{x})$를 **스펙트럼 밀도(spectral density)**라고 하며 이것의 스펙트럼 표현(spectral representation)은 
$$
C(\mathbf{h})=\int_{\mathbb{R}^{d}}\exp(i\mathbf{h}^{T}\mathbf{x})f(\mathbf{x})d\mathbf{x}=\int_{\mathbb{R}^{d}}\cos(\mathbf{h}^{T}\mathbf{x})f(\mathbf{x})d\mathbf{x}
$$
로 쓸 수 있다.

이 정리를 쓰면 상대적으로 쉽게 어떤 함수가 양정치함수임을 보일 수 있다. 즉
$$
C(\mathbf{h}) =\int_{\mathbb{R}^{d}}\exp(i\mathbf{h}^{T}\mathbf{x})dF(\mathbf{x})
=\int_{\mathbb{R}^{d}}\exp(i\mathbf{h}^{T}\mathbf{x})f(\mathbf{x})d\mathbf{x}
$$
임을 보이고 $f(\mathbf{x})$가 양(positive)임을 보이기만 하면 된다.

## 콜모고로프 존재 정리(Kolmogorov's existence theorem)

정상성이 아닌 경우에는 **콜모고로프 존재 정리(Kolmogorov's existence theorem)**으로 해결할 수 있다고 한다.

## 공분산함수의 성질(properties of covariance functions)

여기서부터는 공분산함수(covariance function) $C(\mathbf{h})$의 성질에 대해 다루겠다.

- $C(\mathbf{0}) \geq 0$ (분산이 음이 아님)

- $C(\mathbf{-h})=C(\mathbf{h})$

- $|C(\mathbf{h})| \leq C(\mathbf{0})$ (코쉬-슈바르츠 부등식)

- $C_{1}$, $C_{2}$가 양정치함수이면 $a_{1}C_{1}+a_{2}C_{2}$ 또한 양정치함수이다. ($a_{1}$, $a_{2} \geq 0$) 추가적으로 $C_{1}C_{2}$ 또한 양정치함수이다.

- $C_{1}, C_{2}, \ldots$가 양정치함수의 수열이고 이것의 극한 $\lim_{n \rightarrow \infty}C_{n}$이 존재하면 이것 또한 양정치함수이다.

### 등방성(isotropy)

$C(\mathbf{h})=C_{0}(\|\mathbf{h}\|)$인(or $\gamma(\mathbf{h})=\gamma_{0}(\|\mathbf{h}\|)$) $C_{0}$가 존재할 경우 이 공간과정이 $Z(\mathbf{s})$를 **등방성(isotropy)**을 갖는다라고 한다. 이것은 $d$차원에서 정의한 $\mathbf{h}$ 1차원인 거리에만 의존하는 공분산함수로 표현 가능하다는 것이다.

### 동질성(homogeneous)

(잘 쓰이지는 않지만) $Z(\mathbf{s})$가 내재적(intrinsic)이고 등방성(isotrophic)인 경우 $Z(\mathbf{s})$를 **동질성(homogeneous)**을 갖는다라고 한다.

### 이등방성(anisotropy)

**이등방성(anisotropy)**란 말 그대로 등방성이 아닌 경우를 얘기하지만 이런 경우가 너무 많아 범위를 나누어 생각한다.

###z3 기하학적 이등방성(Geometric anisotropy)

이것은
$$\gamma(\mathbf{h})=\gamma_{0}(\|A\mathbf{h}\|)$$
즉 어떤 **선형변환행렬(linear transfomation matrix)** $A$를 통해 변환한 후 등방성인 경우를 얘기한다. 보통 $A$는 대칭인 양정치행렬(symmetric positive definite matrix)을 다루며 이 때 $\|A\mathbf{h}\|$는 타원형 등고선(ellipse contour)이 된다.

#### 띠모양 이등방성(zonal anisotropy)

이것은 기하학적 이등방성의 일반화된 버전이라고 생각하면 된다.
$$\gamma(\mathbf{h})=\sum_{i=1}^{K}\gamma_{0}(\|A_{i}\mathbf{h}\|)$$
로 $A$ 대신 $A_{i}$들로 표현할 수 있는 경우를 얘기한다. 즉 $\gamma(\mathbf{h})$에 대응되는 공간과정을 $Z(\mathbf{s})$라 할 때 각 변동도(variogram)에 해당하는 독립인 공간과정(independent spatial process)의 합으로 즉
$$Z(\mathbf{s})=Z_{1}(\mathbf{s})+ \cdots Z_{k}(\mathbf{s})$$
로 표현할 수 있다는 것이다.

여기서 각각은 변동도인데 이들의 합도 변동도인가?라는 궁금증을 가질 수 있다. 이것은 맞다고 한다. 앞서 '공분산함수가 되려면 이 함수가 양정치함수이어야 한다'라는 것에 대해 배운 적이 있다. 변동도에 대해서도 똑같이 생각해 볼 수 있을 것이다. 유효한 변동도(valid variogram)이란 무엇인가? 이를 확인해 보기 위해 다음 정의를 살펴보자.

$\gamma(\mathbf{h})=C(\mathbf{0})-C(\mathbf{h})$라고 하자. 이 때 $C(\mathbf{h})$는 양정치함수이나 $C(\mathbf{0})$의 존재로 $\gamma(\mathbf{h})$가 양정치함수라고 말할 수는 없다. 대신 $\sum a_{i}=0$을 만족하는($C(\mathbf{0})$ 때문에 붙는 조건이다) 임의의 $a_{1}, \cdots a_{n}$에 대해
$$\sum_{i}\sum_{j}a_{i}a_{j}\gamma(\mathbf{s}_{i},\mathbf{s}_{j}) \leq 0$$
인 경우 $\gamma(\mathbf{h})$를 **조건부 음정치(conditionally negative definite)**라고 한다.

우리는 종속구조(dependent structure)를 모델링하기 위해 공분산 준변동도(covariance semivariogram)를 생각하고 있다. 그런데 공간 데이터를 가지고 있으면 이를 어떤 표면(surface)으로 표현 가능하고 이 과정이 부드러운(smooth)지, 즉 과정이 연속인지 또는 미분가능한지 체크해 보고 싶을 수 있다. 이를 공분산을 가지고 체크해 볼 수 있다고 한다. 즉 공분산은 종속구조를 측정하는 것 이외의 또 다른 기능을 갖고 있는 것이다.

## 공간 확률과정의 연속성과 미분가능성(continuity and differentiabiliy of spatial stochastic process

우선 **연속성(continuity)**과 **미분가능성(differentiability)**의 정의를 해야 한다. 여러 버전이 있으나 여기서는 두 가지만 소개하기로 한다.

### 경로연속(path-continuity) 또는 경로 미분가능성(path-differentiability)

어떤 확률과정 $Z(\mathbf{s})$가 **경로연속(path-continuity)** (또는 K번 미분가능(K-times differentiability))하다는 것은 그것의 실현(realization)이 연속(K번 미분가능)한 것이다. 말은 쉬우나 보이기는 어렵다.

$\{ Z(\mathbf{s}) , S \in \mathcal{D}\}$를 확률변수의 모임(collection)이라고 할 때 $(\omega \in \Omega, \mathcal{F}, P)$에서 $\omega$ 하나당 $\{ Z(\mathbf{s})\}$가 나오고 이것을 실현한 것이다.

### 평균제곱연속(mean-square continuity) 또는 평균제곱 미분가능성(mean-square differentiability)

어떤 확률과정 $Z(\mathbf{s})$가 $\mathbf{s}$에서 **평균제곱연속(mean-square continuity)**이라는 것(다른 말로 $L_{2}$-수렴)은
$$E[(Z(\mathbf{s}+\mathbf{h}))^{2}] \stackrel{\|\mathbf{h}\| \rightarrow 0}{\rightarrow} 0$$
인 경우이다.

같은 방법으로 어떤 확률과정 $Z(\mathbf{s})$가 미분계수 $Z'(\mathbf{s})$에 대해  **평균제곱 미분가능(mean-square differentiable)**이라는 것은
$$E[(\frac{Z(\mathbf{s}+\mathbf{h})-Z(\mathbf{s})}{h}-Z'(\mathbf{s}))^{2}] \stackrel{\|\mathbf{h}\| \rightarrow 0}{\rightarrow} 0$$
인 경우이다.

사실 $\frac{Z(\mathbf{s}+\mathbf{h})-Z(\mathbf{s})}{h}$의 극한으로 $Z'(\mathbf{s})$를 정의하는 것이다. 고차원의 경우도 반복적으로 정의가 가능하다. 이것의 생김새로 보아 변동도와 관련이 있을 것이다라는 생각도 해 볼 수 있을 것이다.

그렇다면 이 둘 사이에는 어떤 관계가 있을까? 안타깝께도 내재하는 관계는 없다. 즉 경로연속이나 평균제곱연속은 아닌 경우도 있고 그 반대도 있다.

한편 공분산과 평균제곱연속(또는 미분가능성)은 어떤 연관성이 있는 걸까?
$$E[(Z(\mathbf{s}+\mathbf{h}))^{2}] \stackrel{\|\mathbf{h}\| \rightarrow 0}{\rightarrow} 0$$
으로부터
$$2\gamma(\mathbf{h})=2(C(\mathbf{0})-C(\mathbf{h})) \stackrel{\|\mathbf{h}\| \rightarrow 0}{\rightarrow} 0$$
즉 $C$라는 함수가 $\mathbf{0}$에서 연속이라는 것을 알 수 있다.

(약)정상성을 가정할 경우 ($\mathbf{s} \in \mathbb{R}^{d}$, $\mathbf{s}$는 고정되어있지 않다)
$$ \mathbf{s} \text{에서 평균제곱연속} \leftrightarrow C(\cdot)\text{이 } \mathbf{0}\text{에서 연속}$$
$$C(\cdot)\text{이 } \mathbf{0}\text{에서 연속} \rightarrow Z(\mathbf{s})\text{가 모든 지점에서 평균제곱연속}$$
위 결과로부터, $Z(\mathbf{s})$는 모든 지점에서 평균제곱연속이거나 어떠한 지점에서도 평균제곱연속하지 못함을 알 수 있다. (어떤 특정한 지역에서만 평균제곱연속할 수 없다)

또한 다음과 같은 사실도 알 수 있다.
$$C(\cdot) \text{가 원점에서 연속이면} \rightarrow C(\cdot) \text{는 모든 지점에서 연속이다}.$$
이것의 증명에 대해서는 각자 생각해보기로 한다.

### Bartlett의 정리(Bartlett's theorem)

이 정리는 다음 두 가지를 일컫는 말이다.

<div class="theorem">

공분산함수 $\rho(\mathbf{u})$를 갖는 정상확률과정이 k-번 평균제곱 미분가능하다는 것은 $\rho(\mathbf{u})$가 원점에서 2k-번 미분가능하다는 것과 동치이다. (k=0일 경우 위에서 말했던 관계와 같다.)

k번 미분가능한 평균제곱 미분계수(k-th mean-square derivative) $Z^{(k)}(\mathbf{s})$의 공분산함수는 $(-1)^{k}C^{(2k)}$이다.

</div>

위 설명 내용은 나중에 공분산 모형으로 체크해 볼 수 있다. 지수 공분산 모형(exponential covariance model)은 미분가능하지 않다. 한편 Matern 계급(class)을 이용할 경우 모수를 조절해서 어느 정도까지 공분산 모형이 미분가능할 지 조절할 수 있다. 한편 비모수적인 방법으로 경험적 변동도(empirical variogram)를 쓸 수 있는데, 이 방법으로는 공분산 모형이 몇 번 미분가능한지 구분할 수 없다.

<div class="example">

(1-d인 경우) $Z_{h}(\mathbf{s})=\frac{Z(\mathbf{s}+\mathbf{h})-Z(\mathbf{s})}{h}$로 정의하고 이것의 공분산함수 $C_{h}(\mathbf{t})$를 계산하면
$$C_{h}(\mathbf{t})=\text{Cov}(Z_{h}(\mathbf{s}+\mathbf{t}),Z_{h}(\mathbf{s}))=\frac{1}{h^{2}}\{2C(\mathbf{t})-C(\mathbf{t}+\mathbf{h})-C(\mathbf{t}-\mathbf{h})\}$$
이다. 만약 $C(\cdot)$이 두 번 미분가능하다면
$$C_{h}(\mathbf{t}) \stackrel{\|\mathbf{h}\| \rightarrow 0}{\rightarrow} -C^{''}(\mathbf{t})$$
이다.

</div>

한편 평균제곱 연속성은 프랙탈 분석(fractal analysis) (표면의 부드러움 체크 관련), first index estimation 등과도 관련된다고 한다.

### Kent의 경로연속을 위한 충분조건(Kent's sufficient condition for path-continuity) (2-d ver)

평균제곱연속이나 경로연속이지 않은 경우(path-continuous 조건이 mean-square continuous조건보다 strong하다)는 것을 보이는 [@Kent1989]의 정리를 소개하였다. 여기서는 간단하게 2-d version으로 정리한다.

<div class="theorem">

$\rho(\mathbf{u})$를 상관함수(correlation function)라고 하자. 이 함수를 테일러 전개로
$$\rho(\mathbf{u})=\rho_{m}(\mathbf{u})+r_{m}(\mathbf{u}), \mathbf{u} \in \mathbb{R}^{2},$$
여기서 $\rho_{m}(\mathbf{u})$는 $\mathbf{u}=\mathbf{0}$에서 전개한 테일러 급수의 m차 다항함수, $r_{m}(\mathbf{u})$는 나머지(remainder)이다.

</div>

이 때, 경로연속이 성립할 충분조건은 $\rho (\cdot)$이 두번 연속 미분가능하고 $|r_{2}(\mathbf{u})|$가 다음의 순서로
$$|r_{2}(\mathbf{u})|=O(\frac{|\mathbf{u}|^{2}}{(\log |\mathbf{u}|)^{3+\gamma}}) \text{ as } |u| \rightarrow 0 \text{ for some } \gamma >0$$
0으로 가는 것이다.

<div class="corollary">

정상 가우스 과정일 때 경로 연속에 대한 충분조건은
$$\rho(\mathbf{0})-\rho(\mathbf{u})=O(\frac{1}{(\log |\mathbf{u}|)^{1+\epsilon}})=o(1) \text{ as } |\mathbf{u}| \rightarrow 0 \text{ for some } \epsilon > 0$$
이다. 왼쪽의 $\rho(\mathbf{0})-\rho(\mathbf{u})$은 가우스 과정일 경우 나머지의 차수(order)가 아닌 상관(correlation)의 차수로 표현 가능하다는 뜻이다.

</div>

분산 1일 시
$$\rho(\mathbf{0})-\rho(\mathbf{u})=\gamma(\mathbf{u}) \stackrel{\|\mathbf{u}\| \rightarrow 0}{\rightarrow} 0$$
이며 이 화살표는 평균제곱 연속성의 정의와 같다. ($\rho(\mathbf{0})-\rho(\mathbf{u})=o(1)$)

한편 corollary의 차수보다 천천히 0으로 가면 평균제곱 연속은 되지만 경로연속이 되지는 않는다.

