# 공간 극단값 이론과 최대안정과정 {#spatextremes}

이 절은 **최대안정과정(max-stable process)** 및 이것의 **공간 극단값(spatial extremes)**이론으로의 응용에 초점을 맞춰 서술한다. 이 절의 서술 내용은 [@Coles2001]과 [@Dey2015]를 참고하였다.

## 최대안정과정(max-stable process)

앞서 나왔던 **최대안정(max-stable)**의 정의를 다시 살펴보자. 이번엔 [@Dey2015] 버전이다.

<div class="definition"> 

$Z_{1}, Z_{2},\ldots$를 확률과정 $\{Z(x):x\in\mathcal{X} \}$의 독립인 copy들의 수열이라고 하자. 만약 각각의 $n, (n\geq 1)$에 대해 다음과 같은 $a_{n}>0$, $b_{n}\in\mathbb{R}$이 존재해 다음
\begin{equation}
\frac{\max_{i=1,\ldots ,n}Z_{i}-b_{n}}{a_{n}}\stackrel{d}{=}Z
\end{equation}
을 만족한다면 $\{Z(x):x\in\mathcal{X} \}$를 **최대안정(max-stable)**하다고 말한다.

</div>

다음은 [@DeHaan1984]에 나오는 정리이다.

<div class="theorem"> 

$Y_{1}, Y_{2},\ldots$를 continuous sample path를 갖는 $\{Y(x):x\in\mathcal{X} \}$의 독립인 copy들의 수열이라고 하자. 만약 연속함수 $c_{n}>0, d_{n}\in\mathbb{R}$이 존재해 극한과정(limiting process) $\{Z(x): x\in\mathcal{X}\}$에 수렴한다면, 즉
\begin{equation}
\frac{\max_{i=1,\ldots, n}Y_{i}(x)-d_{n}(x)}{c_{n}(x)}\rightarrow Z(x), x\in\mathcal{X}, n\rightarrow \infty \label{eq:dehaan}
\end{equation}
이고 $Z(x)$가 non-degenerate라면 $\{Z(x):x\in\mathcal{X} \}$ **최대안정과정(max-stable process)**이어야 한다. (\@ref(eq:dehaan))의 수렴은 $\mathcal{X}$의 연속함수 공간에서의 약수렴(weak convergence)을 의미한다.

이 정리의 의미는 다음과 같다. 일변량 극단값 이론과 연관성을 생각해보면 $\{Z(x):x\in\mathcal{X} \}$는 일반화 극단값 분포여야 한다는 것이다.

</div>

공간 극단값 이론에서 최대안정과정을 고려하는 이유는 다음과 같다. $n$개의 독립 반복에서 극한과정(limiting process) $\{Z(x): x\in\mathcal{X}\}$이 $n$이 충분히 클 때 **부분 최대 과정(partial maxima process)**을 모델링 할 좋은 후보라고 여겨지기 때문이다.

<div class="definition"> 

(margin이 unit Fréchet $(F(z)=\exp(-1/z))$이라고 가정하자.) 이러한 경우에
\begin{equation}
\max_{i=1,\ldots , n}n^{-1}Z_{i}(\cdot) \stackrel{d}{=} Z(\cdot), n\geq 1
\end{equation}
일 경우 과정(process) $\{Z(x)\}$를 **최대안정과정(max-stable process)**이라고 부른다.

</div>

이 때 놀랍게도 최대안정과정에서 **spectral characterization** (뜻 찾아보기)를 얻는 것이 가능하다고 한다.

<div class="definition"> 

([@DeHaan1984]의 characterization) $\{ (\xi_{i}, U_{i})\}_{i \geq 1}$을 $(0,\infty ] \times \mathbb{R}^{d}$에서 (intensity $d\Gamma (\xi, u)=\xi^{-2}d\xi\nu(du), \nu$는 $\mathbb{R}^{d}$에서 $\sigma$-finite measure)의 **Poisson point process**의 점들이라고 하자. 그리고 $\{Z(x) \}_{x\in\mathbb{R}^{d}}$는 unit Fréchet margin을 가지는 최대안정과정이라고 가정하고 continuous sample path에서
\begin{equation}
\{Z(x)\}_{x\in\mathbb{R}^{d}}\stackrel{d}{=}\{\max_{i\geq 1}\xi_{i}f_{x}(U_{i})\}_{x\in\mathbb{R}^{d}}
\end{equation}
를 만족한다. 그러면 다음과 같은은 음이 아닌 연속함수
$$\{ f_{x}(y):x,y\in\mathbb{R}^{d}\}$$
가 존재해
\begin{equation}
\int_{\mathbb{R}^{d}}f_{x}(y)\nu(dy)=1, \forall x \in \mathbb{R}^{d}
\end{equation}
를 만족한다.

</div>
