# (PART) Spatio-Tempral Statistics {-}

# 시공간 통계학 {#spatiotemporal}

이 장의 전체적인 내용 및 수학 기호 표시는 [@Cressie2015]를 따라가려고 한다. R-code로 참고할 만한 논문은 [@Padoan2015]가 있다. 또 다른 참고할 만한 책으로는 [@Montero2015]로, 이 책의 5장부터 내용을 참고했다.

## 가우스 확률장(Gaussian random fields)

<div class="definition">

시공간 확률장 $Y(\mathbf{s},t)$가 임의의 $\{(\mathbf{s}_{1},t_{1}),\ldots , (\mathbf{s}_{n},t_{n})\}$에 대해 무작위 벡터 $\mathbf{Y}=(Y(\mathbf{s}_{1},t_{1}),\ldots , Y(\mathbf{s}_{n},t_{n}) )'$가 다변량 가우스 분포(multivariate Gaussian distribution)를 따를 때, 이 확률장을 **가우스 확률장(Gaussian random fields)**이라고 한다.

</div>

$\{ Y(\mathbf{s},t), (\mathbf{s},t) \in \mathcal{I}\}$를 $\mathcal{I}$에서 정의된 실수값을 갖는 확률과정(random process)이라고 하자. 이 때 $\mathcal{I}=\mathcal{S}\times\mathcal{T}, \mathcal{S}\subseteq \mathbb{R}^{d}, \mathcal{T}\subseteq \mathbb{R}$이다. $\mathcal{I}=\mathcal{S}$이면 $Y(\mathbf{s})\equiv Y(\mathbf{s},t_{0})$이면 공간 확률장(spatial random field)이 된다. 마찬가지로 $\mathcal{I}=\mathcal{T}$이면 $Y(\mathbf{t})\equiv Y(\mathbf{s}_{0},t)$은 시간 확률장(temporal random field)이 된다. $I:=\{1,\ldots , l\}$과 $J:\{ 1, \ldots, k \}$를 index set이라고 놓고 이들의 데카르트 곱(Cartesian product)을 $I^{*}=I\times J$라고 놓자. 그리고 이것의 카디널리티를 $m=k\cdot l$이라고 놓자. 

간단히 하기 위해 $Y(\mathbf{s},t)$가 약정상성(second-roder stationary)을 따르는 시공간 가우스 확률장이라고 놓자. 이 뜻은
$$\forall (\mathbf{s},t)\in\mathcal{I}, E[Y(\mathbf{s},t)]=\mu, \qquad{\text{Var}[Y(\mathbf{s},t)]=\omega{2}}$$
$$\forall (\mathbf{s},t), (\mathbf{s}',t)\in\mathcal{I}, \text{cov}[Y(\mathbf{s},t), Y(\mathbf{s}',t)]=E[Y(\mathbf{s},t), Y(\mathbf{s}',t)]-\mu^{2}$$
이다. 마지막 공분산과 관련된 조건은 $C(\mathbf{h}, u)$가 이동불변성(translation invariant)을 갖는다고 볼 수 있다. $C(\cdot, \cdot)$는 양의 정부호 함수(positive definite function)로 $\mathbf{h}=\mathbf{s}'-\mathbf{s}$와 $u=t'-t$에만 의존하는 함수다. 이럴 경우에 $Y$는 시간 및 공간에 대해 **정상 공분산함수(stationary covariance function)**를 갖는다고 말한다. 그러면 $Y$의 분산은 시간 또는 공간의 위치의 영향을 받지 않게되며
$$V(Y(\mathbf{s},t))=C(\mathbf{0},0)=\sigma^{2}, \forall (\mathbf{s},t)\in\mathbb{R}^{d}\times\mathbb{R}$$
과 같이 표현할 수 있다. 이 때 $C(\mathbf{0},0)$은 무작위장의 **사전분산(priori variance)**이라 불린다.

$Y$의 상관관계 함수는(correlation function)
$$\rho (\mathbf{h}, u )=\frac{C(\mathbf{h}, u )}{C (\mathbf{0}, 0 )}$$
가 된다. 

<div class="definition">

시공간 확률장 $Y(\mathbf{s},t)$의 공분산함수가 임의의 시공간 장소 $(\mathbf{s}_{i}, t_{i}),(\mathbf{s}_{j}, t_{j})\in\mathbb{R}^{d}\times \mathbb{R}$에 대해 다음과 같이
$$C((\mathbf{s}_{i}, t_{i}), (\mathbf{s}_{j}, t_{j}))=C_{s}(\mathbf{s}_{i},\mathbf{s}_{j})C_{t}(t_{i},t_{j})$$
시간에 대한 공분산함수 $C_{s}$와 공간에 대한 공분산함수 $C_{t}$로 분해될 때, 이 공분산함수 $C$가 **분리가능(separable)**하다고 한다.

</div>

<div class="definition">

시공간 확률장 $Y(\mathbf{s},t)$의 **시공간 변동도(spatio-temporal variogram)**는
$$2\gamma((\mathbf{s}_{i},t_{i}), (\mathbf{s}_{j},t_{j}))=V(Y(\mathbf{s}_{i},t_{i})-Y(\mathbf{s}_{j},t_{j}))$$
로 정의된다. 이것의 절반을 **시공간 준변동도(spatio-temporal semivariogram)**으로 정의한다. 만약 상수 평균값을 갖는 시공간 확률장이라면,\
$$\gamma((\mathbf{s}_{i},t_{i}), (\mathbf{s}_{j},t_{j}))=\frac{1}{2}E(Y(\mathbf{s}_{i},t_{i})-Y(\mathbf{s}_{j},t_{j}))^{2}$$
이 된다.

</div>

### 시공간 공분산함수(spatio-temporal covariance)

이 절의 내용은 [@Cressie2015]의 6장 1절을 참고한다.

[@Padoan2015]에서는 실제 현상의 국소 변동성을 묘사하기 위해 시공간 확률장을
$$Y(\mathbf{s}, t)=Y_{0}(\mathbf{s},t) +\epsilon (\mathbf{s},t),$$
으로 놓는다. 여기서 $\epsilon(\mathbf{s},t)\sin\mathcal(0,\tau^{2})$은 $Y_{0}$와 독립인 백색잡읍이다. 이것의 공분산함수는
$$C(\mathbf{h},u)=\tau^{2}I_{\{\mathbf{0},0\}}((\mathbf{h},u))+\sigma^{2}\rho_{0}(\mathbf{h},u), \qquad{(\mathbf{h},u)\in\mathbb{R}^{d}\times \mathbb{R}}$$
로 정의한다. $\sigma^{2}>0$과 $\rho_{0}$은 임의장의 일반적인 분산 및 상관계수이며, $\tau^{2}>0$은 덩어리 효과(nugget effect)를 표현하기 위한 국소 분산(local variance)이다. 그러면 시공간 확률장 $Y(\mathbf{s},t)$의 분산은
$$\omega^{2}=\tau^{2}+\sigma^{2}$$
이고 공분산함수는 $\sigma^{2}\rho_{0}(\mathbf{h},u)$가 된다. 만약 $Y(\mathbf{s},t)$의 내재정상성을 가정한다면 이것의 변동도는
$$2\gamma(\mathbf{h},u)=V\{ Y(\mathbf{s}+\mathbf{h}, t+u\}$$
로 나타낼 수 있다. 이것은 약정상성 아래서는
$$\gamma(\mathbf{h},u)=C(\mathbf{0},0) - C(\mathbf{h}, u)$$
가 된다.

### 시공간 공분산함수와 준변동도의 성질(properties of the spatio-temporal covariance and semivariogram)

[@Montero2015] 5장 4절을 참고한다.
