# 분계점 방법들 {#pot}

지금까지는 블록 최대값으로 모델링하는 방법에 대해 생각해보았다. 그러나 이 방법은 데이터를 낭비한다고도 볼 수 있고, 모든 최대값이 진짜로 극단값인지에 대한 의문이 들게 된다. 즉 어떤 블록의 최대값이 아닌 값들이 다른 블록들의 최대값보다 훨씬 크지만 극단값으로 뽑히지 않는 상황이 발생하게 된다. 만약 시간별 또는 일별 관측값과 같은 상세한 시계열 자료를 얻을 수 있다면 블록화 하는 방법 이외에 다른 방법들 또한 고려해 볼 수 있을 것이다. 일반적으로 임계화를 하는 방법은 좀 더 효율적이지만, 시간 상관관계에 대한 좀 더 상세한 모델링을 필요로 한다. 분계점 방법들에 대한 간단한 리뷰로 [@Scarrott2012]를 참고하길 바란다.

## 일반화 파레토 분포(generalized pareto distribution)

$X_{1},X_{2},\ldots$를 독립적이며 같은 분포를 따르며 분포함수 $F$를 갖는 확률변수들의 수열이라고 하자. 여기서 분계 $u$를 초과하는 $X_{i}$값들을 극단 사건(extreme event)라고 생각할 수 있다. $F$가 알려져 있는 분포라고 한다면
$$P\{X>u+y|X>u\}=\frac{1-F(x+y)}{1-F(u)}, y>0$$
이 성립한다.

주된 결과는 다음 정리에 포함되어 있다.

```{theorem, name="일반화 파레토 분포"}
$X_{1},X_{2},\ldots$이 분포함수 $F$를 갖는 독립인 확률변수의 수열이라고 하자. 그리고
$$M_{n}=\max\{X_{1},\ldots,X_{n}\}$$
을 정의한다. $F$가 극단 종류 정리를 만족한다면 충분히 큰 $n$에 대해
$$P\{M_{n}\leq z\}\approx G(z)$$
이 성립한다. 이때
$$G(z)=\exp\{-[1+\xi(\frac{z-\mu}{\sigma})]^{-1/\xi}\}$$
이며 여기서 $\mu, \sigma>0$이다. 그리고 충분히 큰 $u$에 대해 $X>u$일 때 $(X-u)$의 분포함수는
\begin{equation}
H(y)=1-(1+\frac{\xi y}{\tilde{\sigma}})^{-1/\xi}
\end{equation}
로 근사할 수 있다. 이 때 $\{ y: y > 0 \text{ and } (1+\xi y / \tilde{\sigma}) >0 \}$이며
\begin{equation}
\tilde{\sigma}=\sigma + \xi (x-\mu)
\end{equation}
이다.

```

앞선 정리는 $H(y)$를 $u$가 증가함에 따라 수렴하는 극한 분포라고 생각하여 간간히 할 수 있다. $H(y)$로 정의되는 족(family)들을 **일반화 파레토 족(generalized Pareto family)**이라고 부른다. 앞선 정리는 블록 최댓값이 근사 분포 $G$를 갖으면, 임계 초과들은 일반화 파레토 족에서 근사하는 분포를 찾을 수 있다는 것이다. 더 나아가 , GPD의 모수들은 그것과 연관된 GEV 분포에 의해 유일하게 결정된다. 예를 들면, 앞선 정리에서 나오는 $\xi$는 대응되는 GEV 분포에서의 $\xi$와 정확하게 같다. 한 가지 다른 점이 있다면 GEV 분포의 모수와는 다르게 block size에 invariant하다는 것이다.

이런 GEV 분포와 GPD 사이의 duality는 GEV 분포에서처럼 모수 $\xi$가 GPD의 질적인 행동을 결정하는 데 가장 큰 역할을 한다는 것을 말해준다. $\xi<0$이면 초과의 분포는 $u-\tilde{\sigma}/\xi$의 upper bound를 갖는다. 만약 $\xi=0$이면 분포는 unbounded이고 $H(y)$에서 $\xi \rightarrow 0$인 극한을 취해 다음의 식을 얻는다.

\begin{equation}
H(y)=1-\exp(-\frac{y}{\tilde{\sigma}}), y > 0.
\end{equation}

이 식은 모수가 $1/\tilde{\sigma}$인 지수 분포에 대응된다.

## 분계 초과의 모델링(modeling threshold excesses)

### 분계점 선택(threshold selection)

원래 자료가 i.i.d measurement $x_{1}, \ldots, x_{n}$으로 구성되어 있다고 하자. 극단 사건들은 high threshold $u$로 정의된다. 즉 $\{x_{i}: x_{i}>u\}$로 구성된 임과 초과들로 정의된다. 이러한 초과값들을 $x_{(1)}, \ldots , x_{(k)}$라고 이름붙이고 threshold excesses를 $y_{j}=x_{(j)}-u, j=1,\ldots, k$라고 정의하자. 앞선 GPD 정리에 따라 $y_{j}$는 분포를 GP족의 한 멤버로 근사할 수 있는 random variable의 independent realization으로 간주할 수 있다. 추론은 관찰된 임계 초과의 GP족의 적합, 모델 적합과 외삽으로 구성된다.

GPD에서 threshold를 선택하는 문제는 block maxima 접근에서 block size를 고르는 문제와 유사한다. 이 경우에는 임계가 너무 낮으면 모형의 asymptotic bias를 위반할 수 있다. 너무 높으면 초과되는 값이 적어져 추정시 큰 분산을 만들게 된다. 일반적으로는 limit model이 reasonable approximation을 할 수 있도록 가능한 한 낮은 임계를 잡아주는 것이 좋다고 한다. 이러한 목적으로 두 가지 방법이 가능하다.

1. 모형 추정 전에 탐색적 기법들을 사용한다.

2. 모델을 다른 임계점들에 대해 적합해보고 추정된 모수의 안정성을 평가해 본다.

첫 번째 방법은 GPD의 평균에 기반한 방법이다. $Y$가 모수 $\sigma, xi$인 GPD 분포를 따른다면
\begin{equation}
E(Y)=\frac{\sigma}{1-\xi}, \xi<1
(\#eq:meanGPD)
\end{equation}
이 된다. 만약 $\xi\leq 1$이면 평균은 무한대다. GPD가 수열 $X_{1},\ldots, X_{n}$으로부터 생성되고 임계가 $u_{0}$인 초과의 모델로서 유효하다고 가정해보자. 그러면 \@ref(eq:meanGPD)에 의해
\begin{equation}
E(X-u_{0}|X >u_{0})=\frac{\sigma_{u_{0}}}{1-\xi}, \xi < 1
\end{equation}
을 얻을 수 있다. 그런데 GPD가 $u_{0}$보다 큰 임계에 대해서도 유효해야 GPD가 유효하다고 볼 수 있으므로, 모든 $u>u_{0}$에 대해 $\sigma_{u_{0}}$또한 적절히 변해야 한다. 따라서, $u>u_{0}$일 떄 $\tilde{\sigma}=\sigma + \xi (x-\mu)$ 관계에 의해
\begin{align*}
E(X-u|X>u)&= \frac{\sigma_{u}}{1-\xi}\\
&=\frac{\sigma_{u_{0}}+\xi u}{1-\xi}
\end{align*}
를 얻는다. 따라서 $u>u_{0}$일 때 $E(X-u|X>u)$는 $u$에 대한 선형 함수여야 한다. 즉 $u$에 따라 선형으로 변하는 추정들은 GP 모형에서 적당하다고 생각할 수 있다.
$$(u,\frac{1}{n_{u}}\sum_{i=1}^{n_{u}}(x_{(i)}-u) : u < x_{\text{max}}),$$
이 때 $x_{(1)},\ldots, x_{(n_{u})}$는 $u$를 초과하는 $n_{u}$개의 관찰값들이고 $x_{\text{max}}$가 $X_{i}$들 중 가장 큰 값이라고 할 때, 이것을 **mean residual plot**이라고 부른다.
