# 다변량 극단값 이론 {#mevtheory}

이 부분은 [@Dey2015]의 2장을 참고하였다.

## 코퓰라(copula)

이변량 또는 다변량 분포를 만들 수 있는 방법으로 **코퓰라(copula)**라는 것이 있다. 이것은 보험학, 금융, 경제 모델링, 생존분석, 극단값, 환경 모델링, 시계열과 생물통계 등에서 최근에 주목을 받고 있다. 이 부분은 [@Mikosch2006]를 참고하였다.

연속 분포 $F$를 갖고 그것의 support에서 역 $F^{-1}$을 갖는 실변수 확률변수 $X$를 생각해보자. 만약 $U$가 $(0,1)$에서 정의된 균등분포일 때 $X\stackrel{d}{=}F^{-1}(U)$와 $F(X)\stackrel{d}{=}U$임을 쉽게 체크할 수 있다.

이제 respective marginal distribution functions $F_{i}$ (assumed to be continous and have inverse on the support of $X_{i}$)를 갖는 $\mathbb{R}^{d}$차원 무작위벡터 $\mathbf{X}=(X_{1},\ldots, X_{d})$를 생각하보자. 1차원일 때와 같은 방법으로 다음의 결과를 얻을 수 있다.
\begin{align*} 
P(X_{1}\leq F_{1}^{-1}(x_{1}),\ldots, X_{d}\leq F_{d}^{-1}(x_{d})) &=  P(F_{1}(X_{1})\leq x_{1}, \ldots, F_{d}(X_{d})\leq x_{d}) \\ 
 &= C(x_{1},\ldots, x_{d}).
\end{align*}
식의 오른쪽에서 $d$차원 분포함수 $C$는 support $[0,1]^{d}$를 갖고 uniform marginal distribution functions를 갖는다. 이 때 이 분포함수 $C$를 벡터 $\mathbf{X}$의 **코퓰라(copula)**라고 부른다. 한편 $\mathbf{X}$의 copula $C$가 주어졌을 때 우리는 분포함수들 $F_{i}$들을 이용해 $\mathbf{X}$의 distribution function을 재구성할 수 있다.
\begin{align*} 
P(X_{1}\leq y_{1}, \ldots, X_{d}\leq y_{d}) &=  P(F_{1}(X_{1})\leq F_{1}(y_{1}), \ldots, F_{d}(X_{d})\leq F_{d}(y_{d})) \\ 
 &= C(F_{1}(y_{1}),\ldots,F_{d}(y_{d})).
\end{align*}
좀 더 넓은 의미로 $[0,1]^{d}$에서 support를 갖고 uniform marginal을 갖는 분포함수들을 코퓰라라고 부른다.

주변 분포 함수들 $F_{i}$에 대한 가정이 주어졌다면, 코퓰라 $C$와 $\mathbf{X}$의 분포 사이에는 일대일 대응관계가 존재한다. 즉, $X_{1},\ldots, X_{d}$의 상관관계 구조는 코퓰라와 주변분포 $F_{i}$로 재구성될 수 있다는 것이다. 그러나 코퓰라 $C$를 갖는 벡터 $\mathbf{X}=(X_{1},\ldots, X_{d})$와 분포함수 $C$를 갖는 $\mathbf{Y}=(F_{1}(X_{1}), \ldots, F_{d}(X_{d}))$의 dependence structure가 같다고 얘기하는 것은 아니다.

예를 들어, 벡터 $\mathbf{X}$의 상관관계가 정의될 경우, 그것은 보통 $\mathbf{Y}$의 상관관계 구조와 다르다. $X_{1},\ldots, X_{d}$가 zero autocorrelation들을 갖는 seond order stationary process에서 얻은 표본들이라고 하자. 이것에 대응되는 $F_{1}(X_{1}), \ldots, F_{d}(X_{d})$들을 매우 correlated되어 있고 따라서 일반적으로 second order stationary가 아닐 것이다. 마찬가지로 spectral measure도 $\mathbf{X}$ with unbounded support에서 make sense한 $\mathbf{Y}$에서는 그렇지 않다.


```{theorem, name="누적 분포 함수와 코퓰라"}
Sklar (1959)의 정리는 코퓰라 이론의 시작점을 제시하였다. [@Yee2015] $F$가 무작위 벡터 $(Y_{1}, Y_{2})$의 CDF이고 marginal이 $F_{1}$, $F_{2}$일 때, 대응되는 copula $C$가 존재해 다음을 만족한다.
$$F(y_{1}, y_{2})=C(F_{1}(y_{1}), F_{2}(y_{2});\boldsymbol{\alpha})=C(u_{1},u_{2};\boldsymbol{\alpha}).$$
모든 $(y_{1}, y_{2})\in\mathbb{R}^{2}$에 대해 $F_{j}$가 연속이라면 $C$는 unique하다고 할 수 있다.

```

우리는 $C$를 dependency parameter $\boldsymbol{\alpha}$를 통해 $F$의 dependence structure 정보를 담고 있는 것으로 볼 수 있다. 보통 $\boldsymbol{\alpha}$는 1차원 또는 2차원이다.

```{example, name="이변량 가우스 코퓰라"}
$\boldsymbol{\alpha}=\rho$일 때 **이변량 가우스 코퓰라(bivariate Gaussian copula)**는
$$C(u_{1}, u_{2}, \rho)=\Phi_{2}(\Phi^{-1}(u_{1}), \Phi^{-1}(u_{2});\rho), -1<\rho < 1, 0\leq u_{j} \leq 1$$
이다.
  
```

[@Yee2015]는 이변량 코퓰라들의 흥미로운 성질들을 적어놓았다.

1. $C(u_{1}, u_{2})=0$ if $u_{1}=0$ and/or $u_{2}=0$

2. $C(u_{1}, 1) =u_{1}$ and $C(1,u_{2})=u_{2}$

3. For $j=1,2$, $C(u_{1}, u_{2})$ is nondecreasing as $u_{j}$ increases, keeping the other agument fixed.

4. $F$로부터 random variates를 생성하기  위한 방법으로 다음의 방법을 사용한다. 그 전에 $u_{j}$가 증가함에 따라 $C(u_{1}, u_{2})$또한 증가한다는 강한 가정이 필요하다.

- $U_{1}$, $U_{2}$를 standard uniform distribution으로부터 독립적으로 만든다.

- $Z_{2}=C_{U_{2}|U_{1}}^{-1}(u_{2})$ where $C_{U_{2}|U_{1}}(u_{2})=\partial C(u_{1}, u_{2})/\partial u_{1}= P(U_{2}\leq u_{2}|U_{1}=u_{1})$ is the conditional for $U_{2}$ given $U_{1}=u_{1}$.

- Then $(U_{1}, Z_{2})\sim F$.

5. 연속 확률 변수 $(Y_{1}, Y_{2})\in\mathbb{R}^{2}$에 대응되는 unique copula는 $Y_{1}$ and/or $Y_{2}$에 continuous monotonic transform을 적용해도 변하지 않는다.


## 극단 정규화(limiting standardization)

$d$차원 **다변량 극단값 분포(multivariate extreme value distribution, MEVD)**은 $d$차원 다변량 분포에서의 random sample의 componentwise maxima의 limiting distribution을 고려하는 데에서 부터 시작하였다. $\{\mathbf{X}_{i}=(X_{i,1},\ldots, X_{i,d}): i=1,\ldots, n \}$을 결합 분포 함수 $F$를 갖고 주변 분포 함수 $F_{1}, \ldots, F_{d}$를 갖는 $d$차원 무작위 벡터의 무작위 표본이라고 하자.


