# 상관관계가 있거나 비정상 수열들의 극단값 {#depextremes}

Huser이 박사논문 21쪽에 따르면 difficulties arise when temporal dependence is present, since extremes tend to cluster at high thresholds. 즉 temporal dependent가 있을 경우 extreme value 또한 뭉쳐서 cluster의 형태로 나오기 때문에 분석이 어려워지게 된다. However, if dependence is properly modeled, the point process approach can also provide some insight into the structure of clusters of exceedances. 그런데 이렇게 되면 temporal dependence가 있다는 얘기가 되고 지금까지 가정하는 extremes들이 독립으로 일어난다는 가정에 위배된다.

## 의존성이 있지만 정상 수열의 최댓값(maxima of dependent but stationary series)

[@Leadbetter1983]은 depdenct process의 극단값들의 성질에 대해 많은 연구를 했다. 그 중 키가 되는 결과는 'Leadbetter's $D(u_{n})$ condition'이라고 부르며 이 조건은 long-range dependence가 충분히 약할 경우 extreme value analysis의 asymptotics에 영향을 미치지 않을 것임을 보장해주는 조건이다.

```{definition, name="Leadbetter의 조건"}
[@Huser2013]의 16쪽 정의 14를 참고하였다. $\mathcal{A}, \mathcal{B} \subset \{ 1, \ldots, n\}$이 각각 인덱스들 $i_{1} < \cdots < i_{p}$와 $j_{1} < \cdots <j_{p}$의 부분집합이며 $j_{1} > i_{p}+l$을 만족한다고 하자. 그리고 $Y_{\mathcal{A}}\leq u$를 사건 $\cap_{i\in\mathcal{A}}\{Y_{i}\leq u\}$를 나타낸다고 하자. 이와 유사하게 $Y_{\mathcal{B}}\leq u$도 정의하자. 그러면 
$$|P(Y_{\mathcal{A}} \leq u_{n} \cap Y_{\mathcal{B}} \leq u_{n}) - P(Y_{\mathcal{A}} \leq u_{n})P(Y_{\mathcal{B}} \leq u_{n})  | \leq \alpha(n,l)$$
을 만족할 때 Leadbetter의 조건 $D(u_{n})$을 만족한다고 말한다. 이 때 $\alpha(n,l_{n})\rightarrow 0$ for some sequence $l_{n}=o(n)$, $l_{n}\rightarrow \infty$ as $n \rightarrow\infty$이다.

```

이 약조건이 말하는 것은 충분히 멀리 떨어진 rare event들은 거의 독립으로 간주해도 된다는 의미다. 예를 들면, lag $n$에서 자기상관관계 $\rho_{n}$을 갖는 가우스 수열에서는 $\rho_{n}\log n \rightarrow 0$ as $n\rightarrow 0$인 경우 [@Beirlant2004] $D(u_{n})$조건을 만족한다. 사실은, 이 조건과 정상성 조건을 합치면, 어떤 threshold sequence $u_{n}$에 대해 
$$P(M_{n}\leq u_{n} ) = \{ P(M_{\lfloor n/k_{n}\rfloor} \leq u_{n}) \} + o(1)$$
임을 보일 수 있다고 한다([@Beirlant2004]의 371-372쪽). 이 때 $k_{n}$은 어떤 increasing sequence이며 $k_{n}\rightarrow \infty$이다.

## 디클러스터링(declustering of extremes)

Fawcett의 강의노트를 참고한다. 1990년대 중반부터 독립적인 극단값들을 추출해내기 위한 **디클러스터링(declustering)** 방법들이 시작됐다. 가장 자연스럽고 많이 쓰이는 디클러스터링 방법으로 **runs declustering**이라는 방법이 있다.

1. Choose an auxiliary 'declustering parameter' (which we call $\kappa$)

2. A cluster of threshold excesses is then deemed to have terminated as soon as at least $\kappa$ consecutive observations fall below the threshold.

3. Go through the entire series identifying clusters in this way

4. The maximum (or 'peak') observation from each cluster is then extracted, and GPD fitted to the set of cluster peak excesses.

이 방법은 구현하기는 쉬우나 $\kappa$를 고르는 데에 다음과 같은 이슈들이 있다.

- 만약 $\kappa$가 너무 작으면 cluster peak는 독립성을 가정하기에 안전하게 멀지 않다

- 만약 $\kappa$가 너무 크면 우리가 추론하는 데 필요한 cluster exceedance가 너무 적다

[@Fawcett2012]는 모수 추정이 $\kappa$의 선택에 민감할 수 있음을 밝혔으며, $\kappa$는 자주 임의로 선택된다는 것을 보였다.

R 패키지 `ismev`에서는 디클러스터링을 하는 함수가 없어 이것을 하기 위해 Fawcett의 강의노트에서는 코드를 직접 작성하였다.
